apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-cleaner-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-cleaner-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-cleaner-binding
subjects:
  - kind: ServiceAccount
    name: kube-cleaner-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-cleaner-role
  apiGroup: rbac.authorization.k8s.io
